---
name: machina

channels:
  - conda-forge
  - defaults
dependencies:
  # Core Scientific
  - numpy
  - pandas
  - h5py
  # Stats/ML
  - scikit-learn
  - tensorflow
  - xgboost=1.5.1
  - lightgbm
  - statsmodels
  # Plotting
  - matplotlib
  - seaborn
  # Jupyter
  - jupyterlab
  - ipython
  # PIP
  - pip
  - pip:
      - parameter-sherpa
      - tqdm
